### ISSUE TITLE
raw data

### ISSUE THREAD

**Issue by lalala951** [amarallab/transportation_network_evolution#2]
Can you provide the raw data set,please

**Comment by weihualei2017** [comment]
have added data to the dryad. See updated README

**Comment by lalala951** [comment]
Still don't see."doi not found"

**Comment by weihualei2017** [comment]
try now!

**Comment by lalala951** [comment]
> 现在就试试！

I can see now,
Can you fill in the data for Brazil in 2010,2011 and 2012
thanks

**Comment by weihualei2017** [comment]
Please chose [Download All Files (.zip)] on the left panel.

**Comment by lalala951** [comment]
> Please chose [Download All Files (.zip)] on the left panel.

thank you very much!
